### ISSUE TITLE
Mouse Weird Text Selection, unable to select text properly with soft brightness on (<100%)

### ISSUE THREAD

**Issue by fastrizwaan** [F-i-f/soft-brightness#26] opened 2020-11-13 04:13 UTC
If I set Brightness to 100%, this bug won't happen.

As can be seen in this gif, there are 2 mouse cursors visible, the bright one is invisible, but the dark one in the background is what we see.

in Chrome:
![text_selection](https://user-images.githubusercontent.com/1161682/99027926-76981d00-2594-11eb-9fc8-06dd34d70d34.gif)

in Libreoffice Writer:
![selection_bug](https://user-images.githubusercontent.com/1161682/99027963-92032800-2594-11eb-93c9-f26183c21e6c.gif)

Gedit Text editor:
![gedit](https://user-images.githubusercontent.com/1161682/99027974-97f90900-2594-11eb-82d5-e4d4b2b42142.gif)

**Comment by fastrizwaan** [comment] 2020-11-13 04:18
If I set "Mouse Cursor brightness Control" to "OFF"
then bug won't happen.
![mouse_brightness](https://user-images.githubusercontent.com/1161682/99028253-5157de80-2595-11eb-84af-3b2b5a5634cc.gif)

**Comment by F-i-f** [comment] 2020-11-13 05:34
It's likely fixed in the new [version 26](https://github.com/F-i-f/soft-brightness/releases/download/v26/soft-brightness@fifi.org.v26.shell-extension.zip).  It's not available yet on the shell extensions page as the new version is pending review.
If there still are problems, turn on _Debug_ in the extension's settings and restart your shell (ALT-F2 r) or logout and log back in, reproduce the problem, and then attach the output of `journalctl -S '5 minutes ago'` to this issue.

**Comment by F-i-f** [comment] 2021-03-26 04:18
If the issue is recurring, please provide a log file as described in the [comment just above](https://github.com/F-i-f/soft-brightness/issues/26#issuecomment-726531641).

**Comment by F-i-f** [comment] 2022-05-21 05:28
No one has provided a log or feedback for over a year, closing this issue.
Feel free to reopen it if you are still experiencing issues.

**Closed by F-i-f** 2022-05-21 05:28 UTC
Labels: question
