### ISSUE TITLE
Cursor too smal on 4k display

### ISSUE THREAD

**Issue by nikitagrygoriev** [F-i-f/soft-brightness#29] opened 2020-12-10 00:19 UTC
Cursor scaling does not work correctly on a 4k display when mouse cursor brightness control is on.

**Comment by F-i-f** [comment] 2020-12-10 17:30
Thank you for your report.

What do you expect to happen for a 4k display?  I do not have one around to test.
Maybe if you know how to make a screen recording, that would help as well.

Can you check if the Gnome Desktop zoom works as expected?  Turn off the Soft Brightness extension, then turn on Zoom by launching _Settings_, navigating to the _Universal Access_ tab, selecting the _Zoom_ item in the _Seeing_ section and turning it on with the default (Magnification: 2, Magnifier Position: Screen part: Full Screen).  Does the cursor behave as you'd expect?

**Comment by nikitagrygoriev** [comment] 2020-12-11 00:37
> Thank you for your report.
> 
> What do you expect to happen for a 4k display? I do not have one around to test.
> Maybe if you know how to make a screen recording, that would help as well.
> 
> Can you check if the Gnome Desktop zoom works as expected? Turn off the Soft Brightness extension, then turn on Zoom by launching _Settings_, navigating to the _Universal Access_ tab, selecting the _Zoom_ item in the _Seeing_ section and turning it on with the default (Magnification: 2, Magnifier Position: Screen part: Full Screen). Does the cursor behave as you'd expect?

I took a picture of it (the cursor seems to be missing in the screenshots when "Mouse cursor brightness control" is on). As you can see, "Mouse cursor brightness control" breaks the cursor scaling. Perhaps, you are changing the scaling when decreasing the cursor brightness?
![screen](https://user-images.githubusercontent.com/33720703/101846365-107dc600-3b51-11eb-881a-7f3c0f14a22a.png)

**Comment by F-i-f** [comment] 2020-12-12 03:56
Thanks for the picture, it's obviously wrong.

Can you please:
(1) check if the Gnome Desktop zoom works as expected? Turn off the Soft Brightness extension, then turn on Zoom by launching Settings, navigating to the Universal Access tab, selecting the Zoom item in the Seeing section and turning it on with the default (Magnification: 2, Magnifier Position: Screen part: Full Screen). Is the cursor as you'd expect?  (Picture if you can)

(2) Capture a log:
Disable all extensions but Soft Brightness.
Logout.
Log back in.
Send the output of `journalctl -S '5 minutes ago'`.

**Comment by nikitagrygoriev** [comment] 2020-12-21 16:21
Hey, sorry for the late response. Idk if it was due to some updates, but the bug seems to no longer be present. I'll attach the logs and the screenshot in case you still wish to see them (maybe someone else encounters the same bug in the future).
![Screenshot from 2020-12-21 17-12-46](https://user-images.githubusercontent.com/33720703/102798042-d7472080-43b0-11eb-9b37-7eabeeab68f3.png)
[log.txt](https://github.com/F-i-f/soft-brightness/files/5725325/log.txt)

**Comment by F-i-f** [comment] 2020-12-21 16:27
I didn't see anything suspicious with the log.  You didn't seem to have turned "Debug" on for the extension.

Anyhow, happy to hear that the problem doesn't occur anymore.

**Comment by ferrolho** [comment] 2021-01-12 19:43
Hi! Thank you for this nice extension. I'd like to reopen this issue.

I am having an issue with the size of the mouse cursor when the brightness is set to < 100%. (At exactly 100% the issue does not occur.) As you can see below, the mouse cursor is significantly smaller than the normal cursor. This may be related to 4K screens.
![Peek 2021-01-12 19-40](https://user-images.githubusercontent.com/4166093/104364108-0bc07f00-550e-11eb-9908-02afd2b0c361.gif)

This issue may also be related to #26. As shown below, in the new issue text box, there is an offset between the two cursors due to the scale difference.
![Peek 2021-01-12 19-12](https://user-images.githubusercontent.com/4166093/104364100-09f6bb80-550e-11eb-969e-b925a7792566.gif)

Finally, the cursor scale is correct in Zoom accessibility mode:
![Screenshot from 2021-01-12 19-31-42](https://user-images.githubusercontent.com/4166093/104364310-57732880-550e-11eb-9067-fd1344d6dad7.png)

**Comment by F-i-f** [comment] 2021-01-27 07:17
Mmm, the issue has reoccurred.

As a work-around, you should be able to disable the mouse brightness control in the extension's settings (Gnome Tweaks > Extensions > Soft Brightness > Mouse cursor brightness Control > Turn off).
You should be back to a single cursor, at the right size, but not following the brightness anymore.

Can you try to capture a log?
1. Turn on Debug in Soft Brightness settings: Gnome Tweaks > Extensions > Soft Brightness > Debug > On.
2. Disable all extensions but Soft Brightness (if possible)
3. Logout.
4. Log back in.
5. Send the output of journalctl -S '5 minutes ago'.

**Comment by pankaj4u4m** [comment] 2021-02-12 17:59
Same issue! mouse cursor is too small on top bar area. Other places it is fine.

**Comment by WaseemAlkurdi** [comment] 2021-03-28 07:36
@F-i-f Thanks for this fine extension ... it's a life-saver!

Just want to point out that this issue might be due to HiDPI and Wayland - a similar issue happens when mixing finger and stylus input on a touchscreen laptop under GNOME Wayland (I couldn't reproduce this issue exactly, but the closest I've come is that using a stylus with this extension turned on results in two mouse pointers -normal for GNOME-, but the second one -corresponding to the stylus- isn't "shaded" even if the "Mouse cursor brightness control" option is enabled)

**Comment by F-i-f** [comment] 2021-03-28 18:26
If someone affected by the issue could capture a log, that would help:
1. Launch _Tweaks_ (or _Extensions_ on Gnome 40)
2. Navigate to the _Extensions_ tab (if running Gnome _Tweaks_).
3. Disable all extensions but _Soft Brightness_.
4. Enable _Debug_ in the _Soft Brightness_ preferences panel.
5. Logout.
6. Log back in.
7. Send the output of `journalctl -S '5 minutes ago'`.

**Comment by F-i-f** [comment] 2022-05-21 05:27
No one has provided a log or feedback for over a year, closing this issue.
Feel free to reopen it if you are still experiencing issues.

**Closed by F-i-f** 2022-05-21 05:27 UTC
Labels: question
