### ISSUE TITLE
"Mouse Cursor brightness Control" cause window resize mouse pointer misplaced 

### ISSUE THREAD

**Issue by fastrizwaan** [F-i-f/soft-brightness#27] opened 2020-11-13 04:24 UTC
If I set "Mouse Cursor brightness Control" to "OFF" this is what is expected:
![normal_mouse_border_form](https://user-images.githubusercontent.com/1161682/99028562-11452b80-2596-11eb-902f-f9ada9fbfcc6.gif)

bug: the mouse pointer changes shape away from window border, as the actual mouse pointer is hidden it seems; the background mouse pointer is out of place.
![window_mouse_problem](https://user-images.githubusercontent.com/1161682/99028570-1609df80-2596-11eb-88da-770d0f584c00.gif)

**Comment by F-i-f** [comment] 2020-11-13 05:36
Duplicate of #25.

**Closed by F-i-f** 2020-11-13 05:36 UTC
