### ISSUE TITLE
Cursor Doesn't Change Type

### ISSUE THREAD

**Issue by bradleyhop** [F-i-f/soft-brightness#5] opened 2019-06-10 02:04 UTC
The cursor seems to get stuck on a certain type in non-gnome applications. For examples, in Chrome and Firefox, the cursor won't change to a pointer on links. Or it will and then gets stuck as a pointer for a bit. Another, the pointer won't change to text selector when hovering over the search bar in Spotify. The cursor functions as expected despite its appearance. 

The pointer changes to appropriate types in native gnome applications like the file browser, Tweaks, etc.

Using gnome 3.32.2 (arch)

Side note of thanks: just installed the FHD mod for my x230 thinkpad. To adjust brightness with this mod, a kernel or bios patch is needed. Beyond my means, so this extension is an eye-saver. Thanks!

**Comment by F-i-f** [comment] 2019-06-10 04:22
Thank you for your bug report.

Can you please enable debug tracing?  Launch Gnome Tweaks > Extensions > Soft brightness > Gear icon > Debug > Toggle to on.
The please capture your system journal (`journalctl -f > soft-brightness.log`) and reproduce the issue.
Please attach `soft-brightness.log` to this bug report.

Can you also verify that another extension is not interfering with Soft Brightness?
Please disable all extensions except Soft Brightness.  Is the problem still present?

**Comment by F-i-f** [comment] 2019-08-17 05:50
Is this still an issue, and can you reproduce it as decribed in [comment #2](https://github.com/F-i-f/soft-brightness/issues/5#issuecomment-500287112)?

**Comment by F-i-f** [comment] 2019-08-19 19:20
Also, if the problems ever manifests itself again, please turn off "Soft Brightness" and enable the magnifier (under Settings > Universal Access > Zoom).
Is the cursor also inconsistent with the zoom?
(I'm asking since this uses the same code and wondering if it's a shell problem or not).

**Comment by F-i-f** [comment] 2019-11-07 16:54
I've done some further testing and I can reproduce the problem by:
- Have Soft Brightness enabled and the brightness set at less than 100%.
- Start a window move by pressing on Alt, clicking on a window and drag it around.  Note that the cursor changes to "four-arrows" pointing up/down/left/right when this happens.
- Release the mouse button and the Alt key, now hover to the status bar:  the cursor now shows the "four-arrows" pattern instead of the regular mouse cursor.

I can also reproduce the same issue while using the Gnome-Shell built-in Zoom (Settings > Universal Access > Zoom), which indicates it is a Gnome-Shell bug, not a Soft-Brightness one.

**Comment by luetage** [comment] 2020-03-14 19:14
Well, I just did a bugreport for this, let's see what happens.
https://gitlab.gnome.org/GNOME/gnome-shell/issues/2397

**Comment by F-i-f** [comment] 2020-03-14 22:57
Thanks @luetage.

**Comment by matte-Rhorn** [comment] 2020-04-18 17:48
> Also, if the problems ever manifests itself again, please turn off "Soft Brightness" and enable the magnifier (under Settings > Universal Access > Zoom).
> Is the cursor also inconsistent with the zoom?
> (I'm asking since this uses the same code and wondering if it's a shell problem or not).
I can confirm that the cursor dimension is inconsistent. I configured gnome to a scale of 200% if the brightness is not set at 100% in "Soft Brightness" the cursor is displayed to a zoom factor of 100%. As soon as I disable "Soft Brightness" or I set it back to 100% the cursor goes back to be consistent with the rest of the UI at 200%.

**Comment by F-i-f** [comment] 2020-04-23 18:21
@matte-Rhorn, this indicates this is an issue with Gnome-Shell.

**Comment by F-i-f** [comment] 2022-05-21 05:26
Closing that issue as it's pretty old and there's not much to do about it since it's a Gnome Shell issue.

**Closed by F-i-f** 2022-05-21 05:26 UTC
Labels: external dependency
